### PR TITLE
feat: ssh config hardening

### PR DESCRIPTION
**Pull request by kevbarns**
- https://tableaudebord-apprentissage.atlassian.net/browse/DEVOPS-119

Recommend source from audit : https://www.sshaudit.com/hardening_guides.html#ubuntu_22_04_lts

SSH Keys generation was skip as ed25519 keys are already present on server, is it needed ? cc @moroine @antoinebigard 

```
Re-generate the RSA and ED25519 keys
rm /etc/ssh/ssh_host_*
ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ""
ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""

Enable the ED25519 and RSA keys
Enable the ED25519 and RSA HostKey directives in the /etc/ssh/sshd_config file:
echo -e "\nHostKey /etc/ssh/ssh_host_ed25519_key\nHostKey /etc/ssh/ssh_host_rsa_key" >> /etc/ssh/sshd_config
```

### CODE REVIEW

**Comment by kevbarns** [comment]
A tester en sandbox ⚠️

**Comment by antoinebigard** [comment]
Attention, il va falloir faire une update des known host `.bin/infra ssh:known_hosts:update NOM_PRODUIT`

**Review by kevbarns — COMMENTED** [review]
✅

**Comment by kevbarns** [comment]
> Attention, il va falloir faire une update des known host `.bin/infra ssh:known_hosts:update NOM_PRODUIT`

à communiquer sur le slack lors du merge

**Review by antoinebigard — APPROVED** [review]

**Pull request merged**
